### PR TITLE
Create hellofromben.go

### PR DESCRIPTION
**Pull request by Lowkh**
this is a haha file

### CODE REVIEW

**Comment by Lowkh** [comment]
Hi Khairul!! Haha

**Comment by mofodox** [comment]
Hi Ben!

**Comment by xenodus** [comment]
Hello, I fomo

**Comment by Garymjx** [comment]
Hi GUYS!

**Comment by monkeygoessnap** [comment]
+1

**Comment by Smbsg** [comment]
+2

**Comment by ksw95** [comment]
+3

**Comment by sufiansuni** [comment]
Yes. This is a demo. Indeed.

**Pull request closed without merging**
